# Generated by Django 5.2 on 2026-01-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('tipo_practica', models.CharField(max_length=50)),
                ('periodo_academico', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('proyecto', models.CharField(max_length=150)),
                ('actividades', models.TextField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='Docentes.docente')),
            ],
        ),
    ]
