# Generated by Django 5.2 on 2026-01-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
