# Generated by Django 5.2 on 2026-01-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
        ('Estudiantes', '0002_estudiante_correo_institucional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='tipo_practica',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='Docentes.docente')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('docente', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='Estudiantes.grupo'),
        ),
    ]
