# Generated by Django 5.2 on 2026-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0003_remove_estudiante_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_practica',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
