# Generated by Django 5.2 on 2026-01-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
        ('Estudiantes', '0004_estudiante_carrera_estudiante_tipo_practica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docentes.docente'),
        ),
    ]
