# Generated by Django 5.2 on 2026-01-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
        ('Estudiantes', '0005_alter_grupo_options_alter_grupo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='Docentes.docente'),
        ),
    ]
