# Generated by Django 5.2 on 2026-02-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0006_alter_grupo_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='semestre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='actividades',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_institucional',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
