# Generated by Django 5.2 on 2026-02-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0007_remove_estudiante_actividades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='longitud',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='actividades',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='proyecto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
