# Generated by Django 5.2 on 2026-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0009_remove_estudiante_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='proyecto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
