# Generated by Django 5.2 on 2026-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Proyecto')),
                ('coordinador', models.CharField(max_length=150, verbose_name='Coordinador a cargo')),
                ('periodo', models.CharField(max_length=100, verbose_name='Periodo')),
                ('cantidad_estudiantes', models.IntegerField(default=0, verbose_name='Número de Estudiantes')),
            ],
        ),
    ]
