# Generated by Django 5.2 on 2026-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0002_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='cantidad_estudiantes',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='nombre_proyecto',
        ),
        migrations.AddField(
            model_name='programa',
            name='estudiantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programa',
            name='proyecto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa',
            name='coordinador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programa',
            name='periodo',
            field=models.CharField(max_length=100),
        ),
    ]
