# Generated by Django 5.2 on 2026-03-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0003_remove_programa_cantidad_estudiantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='periodo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
